<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$route['default_controller'] = 'welcome';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;
$route['users'] = 'Controlleruser/affichageUser';
$route['type_passager'] = 'ControllerPassager/load_type_passager';
$route['type_personnel'] = 'ControllerPersonnel/load_type_personnel';
$route['gare'] = 'ControllerPersonnel/load_gare';
$route['type_colis'] = 'ControllerColis/load_type_colis';
$route['add_vehicule'] = 'ControllerVehicule/load_vehicule';
$route['personnel'] = 'ControllerPersonnel/load_personnel';
$route['login'] = 'Login/login';
$route['logout'] = 'Login/logout';
$route['dashboard'] = 'Controlleruser/dashboard';
$route['voyage'] = 'Voyage/load_voyage';
$route['colis'] = 'ControllerColis/listeColis';
$route['add_colis']='ControllerColis/add_colis';
$toute['fiche_colis'] = 'ControllerColis/fiche_colis';
$toute['ticket/(:any)'] = 'Voyage/pdf/$1'; 
$route['passager'] = 'ControllerPassager/load_list_passager';
$route['print_recu']='ControllerColis/print_recu';
$route['depenses'] = 'ControllerDepense/load_depense';
